---

- name: Get the current caller identity information
  amazon.aws.aws_caller_info:
  register: aws_info


# see https://github.com/techservicesillinois/splunk-aws-serverless-apps/tree/master/splunk-cloudwatch-logs-processor
# see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CreateSubscriptionFilter.html
# see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html#LambdaFunctionExample
- name: Deploy lambda
  community.aws.lambda:
    name: "{{ aws_lambda }}"
    region: "{{ region }}"
    s3_bucket: billing-lambda-src
    s3_key: generate_report.py.zip
    runtime: "python3.8"
    role: "arn:aws:iam::{{ aws_info.account }}:role/{{ aws_lambda }}"
    handler: "lambda_function.lambda_handler"
    memory_size: 128
    timeout: 5

# TODO way to add layers from Amazon? AWSSDKPandas-Python38

# see https://docs.ansible.com/ansible/latest/collections/community/aws/cloudwatchevent_rule_module.html
- community.aws.cloudwatchevent_rule:
    name: "lambda_{{ aws_lambda }}"
    region: "{{ region }}"
    schedule_expression: "{{ eventbridge_schedule }}"
    description: Run billing report Lambda on schedule
    targets:
      - id: MyTargetId
        arn: arn:aws:lambda:{{ region }}:{{ aws_info.account }}:function:{{ aws_lambda }}
        input: '{"tag-key": "{{ trigger_inputs.tag_key }}", "tag-value": "{{ trigger_inputs.tag_value }}", "tag-value-default": "{{ trigger_inputs.tag_value_default }}", "days": "{{ trigger_inputs.days }}", "show-chart": "{{ trigger_inputs.show_chart }}", "email-from": "{{ trigger_inputs.email_from }}", "email-to": "{{ trigger_inputs.email_to }}"}'
