---

- name: Get the current caller identity information
  amazon.aws.aws_caller_info:
  register: aws_info

- ansible.builtin.include_tasks: aws_iam.yml
- ansible.builtin.include_tasks: aws_lambda.yml
- ansible.builtin.include_tasks: aws_eventbridge.yml
